### ISSUE TITLE
Remove sample_type column from analysis summary file

### ISSUE THREAD

**Issue by mwyczalkowski** [ding-lab/cptac_rna_expression#1]
This is a request for a change in the output format in the next round of development.

Please remove column 5, sample_type, from the analysis_summary output file. This is based on feedback from CPTAC3 folks, who do not like this ad hoc name.  Instead, users will use UUID to look up verbatim GDC name from a different source, and human users can discern the sample type from the ad hoc sample_name

**Comment by ccwang002** [comment]
The analysis summary file now doesn't have `sample_type` column any more.
